Markdown
Najeeba-Qarqin/MarkdownPreviewer pull request #1
Opened 2024-08-14 20:18 UTC by Najeeba-Qarqin

Markdown previewer 
>  In this PR I created react app
> Installed react-markdown
> Created markdown component 
> added a default markdown 
> added a responsive design

2024-08-14 20:30 UTC, Najeeba-Qarqin commented
Hi @Hasinarahman!
Please review my project!

2024-08-14 20:31 UTC, Najeeba-Qarqin commented
Hi @Hasinarahman!
Please review my project!

2024-08-17 03:41 UTC, Hasinarahman commented
@Najeeba-Qarqin 

Excellent work! 💯 
🎉 Great Design Implemented
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Markdown Previewer project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your used the React-Markdown good
✔️Your design is responsive

soo in my point of view that is nothing to say you can mention the teacher for approval.

2024-08-17 03:58 UTC, Najeeba-Qarqin commented
Hello @ahzamir
Please review my project!

2024-08-19 07:09 UTC, ahzamir requested changes
### Hi @Najeeba-Qarqin 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Well done Najeeba, your code passes all the tests and also your codes are clean but still your project design has some issues I pointed out:
  - When the input field is empty it does not have a fixed width so it has some kind of mixing up with the previewer div and does not look great and the opposite with the height, the height of your input field and previewer should be auto so when there is more content there should be more height other than that it should not have fixed height.

![image](https://github.com/user-attachments/assets/7108210d-08ae-4a6b-a995-4210e273b2cd)
![image](https://github.com/user-attachments/assets/e9c37e13-b26b-4196-8013-2367a82fa8f0)

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
❌ Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Markdown Previewer and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-08-19 07:09 UTC, ahzamir commented on src/Markdown.jsx
- Remove this empty file

2024-08-19 07:09 UTC, ahzamir commented on src/Components/MarkdoqnPreveiwer.jsx
> +---
- This is too much for a placeholder, please make it short

2024-08-19 07:09 UTC, ahzamir commented on README.md
> +> This is the Markdown Previewer project created using React it's responsive and a freeCodeCamps frontend library project.
- Add some description about what your project offers or does

2024-08-19 07:09 UTC, ahzamir commented on README.md
> +- I learned how to create a react app.
- Add what you learned specifically in React while working on this project for example:
  - I learned how to use and create React Components
  - I learned how to use React Hooks and especially `useState` to store the markdown previewer data on it
  - ...

2024-08-19 07:09 UTC, ahzamir commented on README.md
> +
- Include the live demo link

2024-08-19 07:09 UTC, ahzamir commented on README.md
- Add the #How To Use section on your project and add the necessary steps like cloning your project, installing dependencies using npm install and running your project on live server using npm start

2024-08-19 19:10 UTC, Najeeba-Qarqin commented
Hello @ahzamir thanks for your helpful feedback. 
I implemented the feedbacks please check it again! :)

2024-09-16 06:37 UTC, ahzamir approved these changes
### Hi @Najeeba-Qarqin  🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/user-attachments/assets/705c0bfb-6700-4ffe-ba68-73646eb36e80)


# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)


 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Markdown Previewer project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-09-17 01:29 UTC, merged